The =sobrieti= IRC bot plugins for supybot

* Overview

The =sobrieiti= bot is composed of 

 - [[https://github.com/frumiousbandersnatch/supybot-code][supybot-code]] :: a lightly modified version of supybot

 - [[https://github.com/frumiousbandersnatch/sobrieti-plugins][sobrieti-plugins]] :: this package, which contains sobrieti-specific
    plugins

* Installation and Configuration

** Install supybot

Install supybot like normal but pull from the above fork.  Setting up
the virtual env is optional but allows to install as a normal user.

#+BEGIN_SRC sh
virtualenv --system-site-packages $HOME/venv/supybot
source $HOME/venv/supybot/bin/activiate
git clone git@github.com:frumiousbandersnatch/supybot-code.git
cd supybot-code
python setup build
python setup install
#+END_SRC

** Install the plugins

The plugins can be used directly from their checked out locations.

#+BEGIN_SRC sh
git clone git@github.com:frumiousbandersnatch/sobrieti-plugins.git
#+END_SRC

** Configuration

Use the =supybot-wizard= to populate a directory with a configuration
file and the other directories and files in the usual manner.
Additional configuration is below.  This can be done by editing the
=.conf= file or from inside IRC after you have identified as the
owner.

 - =supybot.directories.plugins= :: append the location of the
      =plugins/= directory from this package

 - =supybot.reply.whenAddressedBy.strings= :: explicitly add some
      prefixes with the bot's nick like: =sobrieti,= and =sobrieti:=
      and see next.

- =supybot.reply.whenAddressedBy.nick= :: set to =False=.  Coupled
     with the above this will keep the bot from treating casual
     conversation like "sobrieti rocks" as a directive to run the
     (possibly nonexistent) =rocks= commandd.


* History

=sobrieti= is based on the same named [[https://github.com/frumiousbandersnatch/sobrieti][sobrieti]] bot based on a
derivative of phenny/jenni.


* Plugins

** The Sobrieti Plugins

What makes =sobrieti= unique are a few modules in support of the
=#stopdrinking= channel on Snoonet.

 - Snoo :: interact with reddit

 - Steps :: display some tenets of recovery of varying questionability

Not much to do with sobrieti but these packages are written for her.

 - Dice :: let the bot provide some randomness into your life

 - Urban :: urbandictionary.com interface


** External Plugins

Some plugins come from elsewhere but are tracked here and possibly
modified.

 - Markov :: Markov-chain based shenanigans.  Tracked as a [[https://github.com/apenwarr/git-subtree][git-subtree]]
             from git://git.jamessan.com/Supybot/Markov.git

 - Etymology :: copied from =edsu-plugins=

 - Remind :: copied from [[http://www.kreativekorp.com/swdownload/supybot/Remind.zip][here]]

** To port

Some functionality of the original phenny-based sobrieti has yet to be
ported to the supybot-based one.

 - cleverbot :: (=.cb=) channelling CleverBot

 - factoid :: (=.factoid=) there are several factoid type packages
              available.  Several from code4lib but which require old
              sqlite.  This also has a non-function interface.  The
              current corpus should be converted.

 - movie :: (=.movie=) interface to =imdbapi= (rarely used)

 - oblique :: (=.o=) various offloaded functionality (unlikely to port)

 - scores :: (=.addpoint=) upboats for everyone

 - slap :: (=.slap= / =.love=) deliver some negative/positive reinforcement

 - urbandictionary :: (=.ud=) lookups in Urban Dictionary

 - units :: (=.convert=) there is already =math convert= but it works
            slightly differently

 - weather :: (=.weather=) show the current weather (best to defer to RocksBot?)

 - why :: (=.why=) spew bizarrities

 - wiki :: (=.w= and =.wiki=) interface to Wiktionary and Wikipedia

 - wolframalpha :: (=.wa=) interface to Wolfram Alpha

 - responses :: canned responses to certain phrases ("lol", "brb").  

** Ported

 - urls :: watch for URLs and respond with a summary of what is at the
           link.  The Web module handles this.

 - etymology :: (=.ety=) word origins.  The =edsu-plugins= have one.
                The Etymology module handles this.

 - markov :: (=.imitate=) generate verbiage based on someones recent
             messages.  The Markov module handles this.

 - remind :: (=.in=) reminds people to do something at a later time.
             The Remind module handles this.


** Recomended plugins:

#+BEGIN_EXAMPLE
<frumious> list
<frumpy> Admin, Alias, Channel, Config, Dice, Games, Google, Herald,
Later, Math, Misc, News, Note, Owner, Quote, Seen, Snoo, Status,
Steps, String, Time, Topic, URL, and User
#+END_EXAMPLE


* Links

 - http://supybook.fealdia.org/

* Git juggling

The cloaning of upstream into GitHub. 

#+BEGIN_EXAMPLE
git init
git remote add upstream git://git.code.sf.net/p/supybot/code
git fetch upstream
git remote add github git@github.com:frumiousbandersnatch/supybot-code.git
git checkout -b sobrieti upstream/master
git push github sobrieti
#+END_EXAMPLE
